export const ADD_COUNTRY = "ADD_COUNTRY";
export const REMOVE_COUNTRY = "REMOVE_COUNTRY";
export const UPDATE_TRAVEL_DETAILS = "UPDATE_TRAVEL_DETAILS";
export const UPDATE_PRODUCT_SELECTION_STATE = "UPDATE_PRODUCT_SELECTION_STATE";
export const UPDATE_DELIVERY_DETAILS = "UPDATE_DELIVERY_DETAILS";
export const UPDATE_PACKAGES_AND_EXTRAS = "UPDATE_PACKAGES_AND_EXTRAS";
export const TOGGLE_PRODUCT_VISIBILITY = "TOGGLE_PRODUCT_VISIBILITY";
export const TOGGLE_SELECTED_EXTRA = "TOGGLE_SELECTED_EXTRA";
